/****************************************************************
* TianGong RenderLab											*
* Copyright (c) Gaiyitp9. All rights reserved.					*
* This code is licensed under the MIT License (MIT).			*
*****************************************************************/

#include "Input/Event.hpp"

std::unordered_map<TG::Input::KeyCode, wchar_t const*> TG::Input::EventInfo::keysName =
{
	{TG::Input::KeyCode::None, L"None"},
	{TG::Input::KeyCode::LeftMouseButton, L"LeftMouseButton"},
	{TG::Input::KeyCode::RightMouseButton, L"RightMouseButton"},
	{TG::Input::KeyCode::MidMouseButton, L"MidMouseButton"},
	{TG::Input::KeyCode::Backspace, L"Backspace"},
	{TG::Input::KeyCode::Tab, L"Tab"},
	{TG::Input::KeyCode::Enter, L"Enter"},
	{TG::Input::KeyCode::Esc, L"Esc"},
	{TG::Input::KeyCode::Space, L"Space"},
	{TG::Input::KeyCode::PageUp, L"PageUp"},
	{TG::Input::KeyCode::PageDown, L"PageDown"},
	{TG::Input::KeyCode::End, L"End"},
	{TG::Input::KeyCode::Home, L"Home"},
	{TG::Input::KeyCode::LeftArrow, L"LeftArrow"},
	{TG::Input::KeyCode::UpArrow, L"UpArrow"},
	{TG::Input::KeyCode::RightArrow, L"RightArrow"},
	{TG::Input::KeyCode::DownArrow, L"DownArrow"},
	{TG::Input::KeyCode::Insert, L"Insert"},
	{TG::Input::KeyCode::Delete, L"Delete"},
	{TG::Input::KeyCode::Num0, L"Num0"},
	{TG::Input::KeyCode::Num1, L"Num1"},
	{TG::Input::KeyCode::Num2, L"Num2"},
	{TG::Input::KeyCode::Num3, L"Num3"},
	{TG::Input::KeyCode::Num4, L"Num4"},
	{TG::Input::KeyCode::Num5, L"Num5"},
	{TG::Input::KeyCode::Num6, L"Num6"},
	{TG::Input::KeyCode::Num7, L"Num7"},
	{TG::Input::KeyCode::Num8, L"Num8"},
	{TG::Input::KeyCode::Num9, L"Num9"},
	{TG::Input::KeyCode::A, L"A"},
	{TG::Input::KeyCode::B, L"B"},
	{TG::Input::KeyCode::C, L"C"},
	{TG::Input::KeyCode::D, L"D"},
	{TG::Input::KeyCode::E, L"E"},
	{TG::Input::KeyCode::F, L"F"},
	{TG::Input::KeyCode::G, L"G"},
	{TG::Input::KeyCode::H, L"H"},
	{TG::Input::KeyCode::I, L"I"},
	{TG::Input::KeyCode::J, L"J"},
	{TG::Input::KeyCode::K, L"K"},
	{TG::Input::KeyCode::L, L"L"},
	{TG::Input::KeyCode::M, L"M"},
	{TG::Input::KeyCode::N, L"N"},
	{TG::Input::KeyCode::O, L"O"},
	{TG::Input::KeyCode::P, L"P"},
	{TG::Input::KeyCode::Q, L"Q"},
	{TG::Input::KeyCode::R, L"R"},
	{TG::Input::KeyCode::S, L"S"},
	{TG::Input::KeyCode::T, L"T"},
	{TG::Input::KeyCode::U, L"U"},
	{TG::Input::KeyCode::V, L"V"},
	{TG::Input::KeyCode::W, L"W"},
	{TG::Input::KeyCode::X, L"X"},
	{TG::Input::KeyCode::Y, L"Y"},
	{TG::Input::KeyCode::Z, L"Z"},
	{TG::Input::KeyCode::Keypad0, L"Keypad0"},
	{TG::Input::KeyCode::Keypad1, L"Keypad1"},
	{TG::Input::KeyCode::Keypad2, L"Keypad2"},
	{TG::Input::KeyCode::Keypad3, L"Keypad3"},
	{TG::Input::KeyCode::Keypad4, L"Keypad4"},
	{TG::Input::KeyCode::Keypad5, L"Keypad5"},
	{TG::Input::KeyCode::Keypad6, L"Keypad6"},
	{TG::Input::KeyCode::Keypad7, L"Keypad7"},
	{TG::Input::KeyCode::Keypad8, L"Keypad8"},
	{TG::Input::KeyCode::Keypad9, L"Keypad9"},
	{TG::Input::KeyCode::KeypadMutiply, L"KeypadMutiply"},
	{TG::Input::KeyCode::KeypadAdd, L"KeypadAdd"},
	{TG::Input::KeyCode::KeypadSubtract, L"KeypadSubtract"},
	{TG::Input::KeyCode::KeypadPeriod, L"KeypadPeriod"},
	{TG::Input::KeyCode::KeypadDivide, L"KeypadDivide"},
	{TG::Input::KeyCode::F1, L"F1"},
	{TG::Input::KeyCode::F2, L"F2"},
	{TG::Input::KeyCode::F3, L"F3"},
	{TG::Input::KeyCode::F4, L"F4"},
	{TG::Input::KeyCode::F5, L"F5"},
	{TG::Input::KeyCode::F6, L"F6"},
	{TG::Input::KeyCode::F7, L"F7"},
	{TG::Input::KeyCode::F8, L"F8"},
	{TG::Input::KeyCode::F9, L"F9"},
	{TG::Input::KeyCode::F10, L"F10"},
	{TG::Input::KeyCode::F11, L"F11"},
	{TG::Input::KeyCode::F12, L"F12"},
	{TG::Input::KeyCode::LeftShift, L"LeftShift"},
	{TG::Input::KeyCode::RightShift, L"RightShift"},
	{TG::Input::KeyCode::LeftControl, L"LeftControl"},
	{TG::Input::KeyCode::RightControl, L"RightControl"},
	{TG::Input::KeyCode::LeftAlt, L"LeftAlt"},
	{TG::Input::KeyCode::RightAlt, L"RightAlt"},
	{TG::Input::KeyCode::Semicolon, L"Semicolon"},
	{TG::Input::KeyCode::Comma, L"Comma"},
	{TG::Input::KeyCode::Add, L"Add"},
	{TG::Input::KeyCode::Subtract, L"Subtract"},
	{TG::Input::KeyCode::Period, L"Period"},
	{TG::Input::KeyCode::Slash, L"Slash"},
	{TG::Input::KeyCode::BackQuote, L"BackQuote"},
	{TG::Input::KeyCode::LeftBracket, L"LeftBracket"},
	{TG::Input::KeyCode::BackSlash, L"BackSlash"},
	{TG::Input::KeyCode::RightBracket, L"RightBracket"},
	{TG::Input::KeyCode::Quote, L"Quote"},
};

std::unordered_map<TG::Input::EventType, wchar_t const*> TG::Input::EventInfo::eventTypes =
{
	{TG::Input::EventType::None, L"None"},
	{TG::Input::EventType::Press, L"Press"},
	{TG::Input::EventType::Release, L"Release"},
	{TG::Input::EventType::Char, L"Char"},
	{TG::Input::EventType::MouseMove, L"Mouse Move"},
	{TG::Input::EventType::WheelRoll, L"Wheel Roll"},
};