/****************************************************************
* TianGong GraphicLab											*
* Copyright (c) Gaiyitp9. All rights reserved.					*
* This code is licensed under the MIT License (MIT).			*
*****************************************************************/

#include "Input/Event.h"

std::unordered_map<TG::Input::KeyCode, char const*> TG::Input::EventInfo::keysName =
{
	{TG::Input::KeyCode::None, "None"},
	{TG::Input::KeyCode::LeftMouseButton, "LeftMouseButton"},
	{TG::Input::KeyCode::RightMouseButton, "RightMouseButton"},
	{TG::Input::KeyCode::MidMouseButton, "MidMouseButton"},
	{TG::Input::KeyCode::Backspace, "Backspace"},
	{TG::Input::KeyCode::Tab, "Tab"},
	{TG::Input::KeyCode::Enter, "Enter"},
	{TG::Input::KeyCode::Esc, "Esc"},
	{TG::Input::KeyCode::Space, "Space"},
	{TG::Input::KeyCode::PageUp, "PageUp"},
	{TG::Input::KeyCode::PageDown, "PageDown"},
	{TG::Input::KeyCode::End, "End"},
	{TG::Input::KeyCode::Home, "Home"},
	{TG::Input::KeyCode::LeftArrow, "LeftArrow"},
	{TG::Input::KeyCode::UpArrow, "UpArrow"},
	{TG::Input::KeyCode::RightArrow, "RightArrow"},
	{TG::Input::KeyCode::DownArrow, "DownArrow"},
	{TG::Input::KeyCode::Insert, "Insert"},
	{TG::Input::KeyCode::Delete, "Delete"},
	{TG::Input::KeyCode::Num0, "Num0"},
	{TG::Input::KeyCode::Num1, "Num1"},
	{TG::Input::KeyCode::Num2, "Num2"},
	{TG::Input::KeyCode::Num3, "Num3"},
	{TG::Input::KeyCode::Num4, "Num4"},
	{TG::Input::KeyCode::Num5, "Num5"},
	{TG::Input::KeyCode::Num6, "Num6"},
	{TG::Input::KeyCode::Num7, "Num7"},
	{TG::Input::KeyCode::Num8, "Num8"},
	{TG::Input::KeyCode::Num9, "Num9"},
	{TG::Input::KeyCode::A, "A"},
	{TG::Input::KeyCode::B, "B"},
	{TG::Input::KeyCode::C, "C"},
	{TG::Input::KeyCode::D, "D"},
	{TG::Input::KeyCode::E, "E"},
	{TG::Input::KeyCode::F, "F"},
	{TG::Input::KeyCode::G, "G"},
	{TG::Input::KeyCode::H, "H"},
	{TG::Input::KeyCode::I, "I"},
	{TG::Input::KeyCode::J, "J"},
	{TG::Input::KeyCode::K, "K"},
	{TG::Input::KeyCode::L, ""},
	{TG::Input::KeyCode::M, "M"},
	{TG::Input::KeyCode::N, "N"},
	{TG::Input::KeyCode::O, "O"},
	{TG::Input::KeyCode::P, "P"},
	{TG::Input::KeyCode::Q, "Q"},
	{TG::Input::KeyCode::R, "R"},
	{TG::Input::KeyCode::S, "S"},
	{TG::Input::KeyCode::T, "T"},
	{TG::Input::KeyCode::U, "U"},
	{TG::Input::KeyCode::V, "V"},
	{TG::Input::KeyCode::W, "W"},
	{TG::Input::KeyCode::X, "X"},
	{TG::Input::KeyCode::Y, "Y"},
	{TG::Input::KeyCode::Z, "Z"},
	{TG::Input::KeyCode::Keypad0, "Keypad0"},
	{TG::Input::KeyCode::Keypad1, "Keypad1"},
	{TG::Input::KeyCode::Keypad2, "Keypad2"},
	{TG::Input::KeyCode::Keypad3, "Keypad3"},
	{TG::Input::KeyCode::Keypad4, "Keypad4"},
	{TG::Input::KeyCode::Keypad5, "Keypad5"},
	{TG::Input::KeyCode::Keypad6, "Keypad6"},
	{TG::Input::KeyCode::Keypad7, "Keypad7"},
	{TG::Input::KeyCode::Keypad8, "Keypad8"},
	{TG::Input::KeyCode::Keypad9, "Keypad9"},
	{TG::Input::KeyCode::KeypadMutiply, "KeypadMutiply"},
	{TG::Input::KeyCode::KeypadAdd, "KeypadAdd"},
	{TG::Input::KeyCode::KeypadSubtract, "KeypadSubtract"},
	{TG::Input::KeyCode::KeypadPeriod, "KeypadPeriod"},
	{TG::Input::KeyCode::KeypadDivide, "KeypadDivide"},
	{TG::Input::KeyCode::F1, "F1"},
	{TG::Input::KeyCode::F2, "F2"},
	{TG::Input::KeyCode::F3, "F3"},
	{TG::Input::KeyCode::F4, "F4"},
	{TG::Input::KeyCode::F5, "F5"},
	{TG::Input::KeyCode::F6, "F6"},
	{TG::Input::KeyCode::F7, "F7"},
	{TG::Input::KeyCode::F8, "F8"},
	{TG::Input::KeyCode::F9, "F9"},
	{TG::Input::KeyCode::F10, "F10"},
	{TG::Input::KeyCode::F11, "F11"},
	{TG::Input::KeyCode::F12, "F12"},
	{TG::Input::KeyCode::LeftShift, "LeftShift"},
	{TG::Input::KeyCode::RightShift, "RightShift"},
	{TG::Input::KeyCode::LeftControl, "LeftContro"},
	{TG::Input::KeyCode::RightControl, "RightContro"},
	{TG::Input::KeyCode::LeftAlt, "LeftAlt"},
	{TG::Input::KeyCode::RightAlt, "RightAlt"},
	{TG::Input::KeyCode::Semicolon, "Semicolon"},
	{TG::Input::KeyCode::Comma, "Comma"},
	{TG::Input::KeyCode::Add, "Add"},
	{TG::Input::KeyCode::Subtract, "Subtract"},
	{TG::Input::KeyCode::Period, "Period"},
	{TG::Input::KeyCode::Slash, "Slash"},
	{TG::Input::KeyCode::BackQuote, "BackQuote"},
	{TG::Input::KeyCode::LeftBracket, "LeftBracket"},
	{TG::Input::KeyCode::BackSlash, "BackSlash"},
	{TG::Input::KeyCode::RightBracket, "RightBracket"},
	{TG::Input::KeyCode::Quote, "Quote"},
};

std::unordered_map<TG::Input::EventType, char const*> TG::Input::EventInfo::eventTypes =
{
	{TG::Input::EventType::None, "None"},
	{TG::Input::EventType::Press, "Press"},
	{TG::Input::EventType::Release, "Release"},
	{TG::Input::EventType::Char, "Char"},
	{TG::Input::EventType::MouseMove, "Mouse Move"},
	{TG::Input::EventType::WheelRoll, "Wheel Rol"},
};